version: '3.1'

services:
  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul

volumes:
  mysql-vol:
